Test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -13,18 +13,18 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
+    - name: Cache Cypress binary
+      uses: actions/cache@v2
+      with:
+        path: /home/runner/.cache/Cypress
+        key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
+
     - name: Install system dependencies
       run: sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
 
     - name: Install dependencies
       run: npm install
 
-    - name: List contents of node_modules/.bin
-      run: ls -l node_modules/.bin
-
-    - name: Set execution permission for Cypress binary
-      run: chmod +x node_modules/.bin/cypress
-
     - name: Run Cypress tests
       run: |
-        npx cypress run --browser chrome --headless || (echo "Cypress tests failed" && exit 1)
+        npx cypress run --browser chrome --headless --cache-path /home/runner/.cache/Cypress || (echo "Cypress tests failed" && exit 1)
