Today Last

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -13,12 +13,18 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
+    - name: Install system dependencies
+      run: sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
+
     - name: Install dependencies
       run: npm install
 
+    - name: List contents of node_modules/.bin
+      run: ls -l node_modules/.bin
+
     - name: Set execution permission for Cypress binary
-      if: ${{ runner.os == 'Windows' }}
-      run: icacls node_modules\\.bin\\cypress /grant Users:(RX)
+      run: chmod +x node_modules/.bin/cypress
 
     - name: Run Cypress tests
-      run: npx cypress run
+      run: |
+        npx cypress run --browser chrome --headless || (echo "Cypress tests failed" && exit 1)
